import { Flight, Hotel } from '../types';

// Mock flight data
export const mockFlights: Flight[] = [
  {
    id: 'f1',
    airline: 'Delta Airlines',
    flightNumber: 'DL1234',
    departureAirport: 'JFK',
    arrivalAirport: 'LAX',
    departureTime: '08:00 AM',
    arrivalTime: '11:30 AM',
    duration: '3h 30m',
    price: 299.99,
    currency: 'USD',
    stops: 0,
    cabinClass: 'Economy',
  },
  {
    id: 'f2',
    airline: 'American Airlines',
    flightNumber: 'AA5678',
    departureAirport: 'JFK',
    arrivalAirport: 'LAX',
    departureTime: '10:15 AM',
    arrivalTime: '01:45 PM',
    duration: '3h 30m',
    price: 325.50,
    currency: 'USD',
    stops: 0,
    cabinClass: 'Economy',
  },
  {
    id: 'f3',
    airline: 'United Airlines',
    flightNumber: 'UA9012',
    departureAirport: 'JFK',
    arrivalAirport: 'LAX',
    departureTime: '02:30 PM',
    arrivalTime: '06:00 PM',
    duration: '3h 30m',
    price: 275.75,
    currency: 'USD',
    stops: 0,
    cabinClass: 'Economy',
  },
  {
    id: 'f4',
    airline: 'JetBlue',
    flightNumber: 'B6789',
    departureAirport: 'JFK',
    arrivalAirport: 'SFO',
    departureTime: '07:45 AM',
    arrivalTime: '11:15 AM',
    duration: '6h 30m',
    price: 350.25,
    currency: 'USD',
    stops: 0,
    cabinClass: 'Economy',
  },
  {
    id: 'f5',
    airline: 'Southwest',
    flightNumber: 'WN456',
    departureAirport: 'JFK',
    arrivalAirport: 'SFO',
    departureTime: '01:00 PM',
    arrivalTime: '04:30 PM',
    duration: '6h 30m',
    price: 310.00,
    currency: 'USD',
    stops: 1,
    cabinClass: 'Economy',
  },
  {
    id: 'f6',
    airline: 'British Airways',
    flightNumber: 'BA112',
    departureAirport: 'JFK',
    arrivalAirport: 'LHR',
    departureTime: '09:30 PM',
    arrivalTime: '09:45 AM',
    duration: '7h 15m',
    price: 650.00,
    currency: 'USD',
    stops: 0,
    cabinClass: 'Economy',
  },
  {
    id: 'f7',
    airline: 'Air France',
    flightNumber: 'AF345',
    departureAirport: 'JFK',
    arrivalAirport: 'CDG',
    departureTime: '07:15 PM',
    arrivalTime: '08:30 AM',
    duration: '7h 15m',
    price: 675.50,
    currency: 'USD',
    stops: 0,
    cabinClass: 'Economy',
  },
  {
    id: 'f8',
    airline: 'Lufthansa',
    flightNumber: 'LH789',
    departureAirport: 'JFK',
    arrivalAirport: 'FRA',
    departureTime: '05:45 PM',
    arrivalTime: '07:00 AM',
    duration: '7h 15m',
    price: 690.25,
    currency: 'USD',
    stops: 0,
    cabinClass: 'Economy',
  },
];

// Mock hotel data
export const mockHotels: Hotel[] = [
  {
    id: 'h1',
    name: 'Grand Hyatt',
    location: 'New York City, NY',
    starRating: 4.5,
    price: 299.99,
    currency: 'USD',
    perNight: true,
    amenities: ['Free Wi-Fi', 'Pool', 'Gym', 'Restaurant', 'Bar', 'Room Service'],
    roomTypes: ['Standard', 'Deluxe', 'Suite'],
    images: ['hotel1.jpg'],
    description: 'Luxury hotel in the heart of Manhattan with stunning city views.',
  },
  {
    id: 'h2',
    name: 'Marriott Downtown',
    location: 'New York City, NY',
    starRating: 4,
    price: 249.50,
    currency: 'USD',
    perNight: true,
    amenities: ['Free Wi-Fi', 'Gym', 'Restaurant', 'Bar'],
    roomTypes: ['Standard', 'Deluxe', 'Suite'],
    images: ['hotel2.jpg'],
    description: 'Modern hotel with excellent amenities in downtown Manhattan.',
  },
  {
    id: 'h3',
    name: 'The Ritz-Carlton',
    location: 'Los Angeles, CA',
    starRating: 5,
    price: 450.00,
    currency: 'USD',
    perNight: true,
    amenities: ['Free Wi-Fi', 'Pool', 'Spa', 'Gym', 'Restaurant', 'Bar', 'Room Service'],
    roomTypes: ['Deluxe', 'Executive', 'Suite', 'Presidential Suite'],
    images: ['hotel3.jpg'],
    description: 'Luxury five-star hotel offering exceptional service and amenities.',
  },
  {
    id: 'h4',
    name: 'Hilton Garden Inn',
    location: 'Los Angeles, CA',
    starRating: 3.5,
    price: 189.99,
    currency: 'USD',
    perNight: true,
    amenities: ['Free Wi-Fi', 'Pool', 'Gym', 'Restaurant'],
    roomTypes: ['Standard', 'Deluxe'],
    images: ['hotel4.jpg'],
    description: 'Comfortable and affordable hotel with great amenities.',
  },
  {
    id: 'h5',
    name: 'Four Seasons',
    location: 'San Francisco, CA',
    starRating: 5,
    price: 499.99,
    currency: 'USD',
    perNight: true,
    amenities: ['Free Wi-Fi', 'Pool', 'Spa', 'Gym', 'Restaurant', 'Bar', 'Room Service'],
    roomTypes: ['Deluxe', 'Executive', 'Suite', 'Presidential Suite'],
    images: ['hotel5.jpg'],
    description: 'Luxury hotel with breathtaking views of San Francisco Bay.',
  },
  {
    id: 'h6',
    name: 'Holiday Inn Express',
    location: 'San Francisco, CA',
    starRating: 3,
    price: 159.99,
    currency: 'USD',
    perNight: true,
    amenities: ['Free Wi-Fi', 'Gym', 'Complimentary Breakfast'],
    roomTypes: ['Standard', 'Deluxe'],
    images: ['hotel6.jpg'],
    description: 'Comfortable and affordable hotel with complimentary breakfast.',
  },
  {
    id: 'h7',
    name: 'The Savoy',
    location: 'London, UK',
    starRating: 5,
    price: 550.00,
    currency: 'USD',
    perNight: true,
    amenities: ['Free Wi-Fi', 'Pool', 'Spa', 'Gym', 'Restaurant', 'Bar', 'Room Service'],
    roomTypes: ['Deluxe', 'Executive', 'Suite', 'Royal Suite'],
    images: ['hotel7.jpg'],
    description: 'Iconic luxury hotel on the River Thames with elegant rooms and suites.',
  },
  {
    id: 'h8',
    name: 'Le Méridien',
    location: 'Paris, France',
    starRating: 4.5,
    price: 375.50,
    currency: 'USD',
    perNight: true,
    amenities: ['Free Wi-Fi', 'Pool', 'Spa', 'Gym', 'Restaurant', 'Bar', 'Room Service'],
    roomTypes: ['Classic', 'Deluxe', 'Suite'],
    images: ['hotel8.jpg'],
    description: 'Elegant hotel in the heart of Paris with stunning views of the Eiffel Tower.',
  },
]; 